
GET http://localhost:3001/api/persons
###

GET https://mysterious-atoll-39806.herokuapp.com/info
###

DELETE http://localhost:3001/api/persons/3
###

POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "san",
    "number": "794-888-63"
}