
GET https://mysterious-atoll-39806.herokuapp.com/api/persons
###

GET https://mysterious-atoll-39806.herokuapp.com/info
###

DELETE https://mysterious-atoll-39806.herokuapp.com/api/persons/3
###

POST https://mysterious-atoll-39806.herokuapp.com/api/persons
content-type: application/json

{
    "name": "san",
    "number": "794-888-63"
}